export const MUTATION_CONSTANTS = {
    PUSH_QUESTION: 'PUSH_QUESTION',
    ADD_CATEGORIES: 'ADD_CATEGORIES',
    ADD_STATS: 'ADD_STATS',
    INCREMENT_STATS: 'INCREMENT_STATS',
    SET_QUIZ: 'SET_QUIZ',
    RESET_PROGRESS: 'RESET_PROGRESS',
    UPDATE_QUIZ_PROGRESS: 'UPDATE_QUIZ_PROGRESS',
    RESET_QUIZ: 'RESET_QUIZ',
}
